aws-samples/amazon-bedrock-workshop

- 05_Image/README.md
Revise markdown content: Clarify image prompting, correct typos, grammar, improve structure, and enhance pattern descriptions.
> Correcting README.md

- 00_Intro/bedrock_boto3_setup.ipynb
- 03_QuestionAnswering/01_qa_w_rag_claude.ipynb
- 04_Chatbot/00_Chatbot_AI21.ipynb
- 04_Chatbot/00_Chatbot_Claude.ipynb
- 04_Chatbot/00_Chatbot_Titan.ipynb
- Update BedrockEmbeddings to use latest embeddings model v2.
- Tidy up from typos and text, mainly in chatbot notebooks (reference to GPT-J, Chroma, etc).
> update workshop with new titan embeddings

- 07_Agents/00_LLM_Claude_Agent_Tools.ipynb
- 07_Agents/01_LLM_Claude_Agent_Stock_Analysis.ipynb
Added code sample for using Langchain agents with Amazon Bedrock. The Agents folder contains 2 notebooks, the first one is an introductory notebook with simple examples and the second one is an end to end use case for stock analysis. 
> added sample code for langchain agents integration with Bedrock

- 03_QuestionAnswering/02_qa_w_rag_claude_pinecone.ipynb
> Adding RAG notebook w/ Claude-v1 & Pinecone Vector Database

- 00_Intro/bedrock_boto3_setup.ipynb
- 01_Generation/00_generate_w_bedrock.ipynb
- 01_Generation/01_zero_shot_generation.ipynb
- 01_Generation/02_contextual_generation.ipynb
- 02_Summarization/01.small-text-summarization-claude.ipynb
- 02_Summarization/01.small-text-summarization-titan.ipynb
- 02_Summarization/02.long-text-summarization-titan.ipynb
- 03_QuestionAnswering/00_qa_w_bedrock_titan.ipynb
- 03_QuestionAnswering/01_qa_w_rag_claude.ipynb
- 03_QuestionAnswering/02_qa_w_rag_claude_pinecone.ipynb
- 04_Chatbot/00_Chatbot_AI21.ipynb
- 04_Chatbot/00_Chatbot_Claude.ipynb
- 04_Chatbot/00_Chatbot_Titan.ipynb
- 06_CodeGeneration/00_code_generatation_w_bedrock.ipynb
- 06_CodeGeneration/01_sql_query_generate_w_bedrock.ipynb
- 06_CodeGeneration/02_code_interpret_w_langchain.ipynb
- 06_CodeGeneration/03_code_translate_w_langchain.ipynb
- 07_Agents/00_LLM_Claude_Agent_Tools.ipynb
- 07_Agents/01_LLM_Claude_Agent_Stock_Analysis.ipynb
> Updated langchain version to 0.0.304

- 03_QuestionAnswering/01_qa_w_rag_claude.ipynb
You get a SQL Alchemy error when loading up the VectorDB in this notebook.  
Issue #59 
Add a pip install --upgrade sqlalchemy to the dependency install cell in the notebook.  
> Upgrade SQLAlchemy in 01_qa_w_rag_claude

- 03_QuestionAnswering/03_qa_w_rag_bedrock_titan_pgvector.ipynb
*Issue #97 *
https://github.com/aws-samples/amazon-bedrock-workshop/issues/97
> Add pattern to store embedding to  postgres as vector store

- 03_QuestionAnswering/02_qa_w_rag_claude_opensearch.ipynb
This commit will bring new example based Claude-V2 and OpenSearch serverles. 
Code includes OSS creation and clean up code. 
> new example with OpenSearch serverles

- 00_Intro/bedrock_boto3_setup.ipynb
- 09_Guardrails/00_llm_guardrails_w_bedrock_nemo.ipynb
#78 unify dependencies
1. dependencies installation moved to 'bedrock_boto3_setup' 
2. minor moderation prompt update
> unify dependencies

- 00_Intro/bedrock_boto3_setup.ipynb
Created a cell to display the image produced by the Stability model
> Displaying image by Stability model

- 02_Summarization/03. long text summarization using LCEL chains on Langchain.ipynb
Adding notebook on long summarization with LCEL formatted chains, Bedrock + Claude v2
> Adding notebook on long summarization with LCEL formatted chains, Bedrock + Claude v2

- 03_QuestionAnswering/01_qa_w_rag_claude.ipynb
*Issue #, if available:* 142
*Description of changes:* Fixed embedding_function chain in vectorstore_faiss object
> [Issue 142] Fixed embedding_function call

- 05_Image/bedrock-titan-multimodal-embeddings.ipynb
updated hard coded region_name to fetch from boto3 session
> updated hard coded region_name to fetch from boto3 session

- 03_QuestionAnswering/knowledge-bases/0_create_ingest_documents_test_kb.ipynb
- 03_QuestionAnswering/knowledge-bases/1_managed-rag-kb-retrieve-generate-api.ipynb
- 03_QuestionAnswering/knowledge-bases/2_customized-rag-retrieve-api-claude-v2.ipynb
- 03_QuestionAnswering/knowledge-bases/3_customized-rag-retrieve-api-langchain-claude-v2.ipynb
*0_create_ingest_documents_test_kb.ipynb* 
- Added pre-requisite section
- Updated `create_index body_json`
- Added wait time after creating  index as it was causing error while creating kb
- Added code to wait for collection to get created.
- Added code for creating and deleting s3 bucket
- Commented code for deleting KB, as it will be used in subsequent notebooks. 
- Added 5 secs wait before calling `RetrieveAndGenerate` API
*01_managed-rag-kb-retrieve-generate-api.ipynb*
- retrieving the kb_id created in notebook `0_create_ingest_documents_test_kb.ipynb`
- updated hard coded region name to fetch from boto3 session.
*2_customized-rag-retrieve-api-claude-v2*
- retrieving the kb_id created in notebook …
> updated knowledge bases to run with Workshop Studio account

- 10_CustomModels/02_fine-tune_and_evaluate_llama2_bedrock_summarization.ipynb
- added the notes in 02 notebook to provide instructions for cleaning up with running 04 notebook.
> additional instructions for cleaning up

- 00_Prerequisites/bedrock_basics.ipynb
- 02_KnowledgeBases_and_RAG/2_Langchain-rag-retrieve-api-mistral-and-claude-v2.ipynb
- 05_Agents/insurance_claims_agent/without_kb/create_and_invoke_agent.ipynb
- 06_OpenSource_examples/00_Langchain_TextGeneration_examples/04_long text summarization using LCEL chains on Langchain.ipynb
- 06_OpenSource_examples/00_Langchain_TextGeneration_examples/05_long-text-summarization-titan Langchain.ipynb
- 06_OpenSource_examples/00_Langchain_TextGeneration_examples/utils/__init__.py
- 06_OpenSource_examples/00_Langchain_TextGeneration_examples/utils/bedrock.py
> Fixing workshop bugs

- 06_OpenSource_examples/00_Langchain_TextGeneration_examples/04_long text summarization using LCEL chains on Langchain.ipynb
- 06_OpenSource_examples/00_Langchain_TextGeneration_examples/05_long-text-summarization-titan Langchain.ipynb
> Adding transformers installer

- 06_OpenSource_examples/02_Langchain_Chatbot_examples/00_Chatbot_Claude.ipynb
- 06_OpenSource_examples/02_Langchain_Chatbot_examples/00_Chatbot_Llama2.ipynb
- 06_OpenSource_examples/02_Langchain_Chatbot_examples/00_Chatbot_Titan.ipynb
- 06_OpenSource_examples/02_Langchain_Chatbot_examples/00_Chatbot_V3_Claude.ipynb
- 06_OpenSource_examples/02_Langchain_Chatbot_examples/00_MutliModal_Claude_search.ipynb
> fixing the pip installs and the imports for open source chatbots

- 00_Prerequisites/bedrock_basics.ipynb
> adding fix for streaming - defensive coding

- 02_KnowledgeBases_and_RAG/0_create_ingest_documents_test_kb.ipynb
- 02_KnowledgeBases_and_RAG/utility.py
Added Claude 3 sonnet to knowledge base, showing answers from different Claude models.
Added some try, except to be able to rerun cells
Minor fixes and comments to have clear instructions for cells
> Added Claude 3 sonnet to knowledge base

- 03_Model_customization/00_setup.ipynb
- 03_Model_customization/01_fine-tuning-titan-lite.ipynb
> typo: not to note in 00_setup.ipynb

- 01_Text_generation/03_qa_with_bedrock_titan.ipynb
Description of changes:
Typo fix as part of the workshop
> chore: typo fix anwer -> answer

- 02_KnowledgeBases_and_RAG/0_create_ingest_documents_test_kb.ipynb
fix typo in 0_create_ingest_documents_test_kb.ipynb file
Fixed typo
> Fix typo 0_create_ingest_documents_test_kb.ipynb

- 00_Prerequisites/Getting_started_with_Converse_API.ipynb
- 04_Image_and_Multimodal/bedrock-titan-image-generator.ipynb
When I run the maskPrompt I get this error "ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: 400 Bad Request: Unable to auto-generate mask image with given input image and mask prompt. 
Added Converse API Example
"
I have commented out the negative Text which is a wrong parameter
> removed wrong param

- 05_Agents/agent.py
*Issue #, if available:* Exception handling error being fixed
> fixing exception handling

- 01_Text_generation/00_text_generation_w_bedrock.ipynb
- 01_Text_generation/01_code_generation_w_bedrock.ipynb
- 01_Text_generation/02_text-summarization-titan+claude.ipynb
- 01_Text_generation/03_qa_with_bedrock_titan.ipynb
- 01_Text_generation/04_entity_extraction.ipynb
*Description of changes: Updated Jupyter notebooks in Text_Generation lab to use Claude 3 models.
> updated Text_Generation lab with Claude 3 models

- 02_KnowledgeBases_and_RAG/0_create_ingest_documents_test_kb.ipynb
- 02_KnowledgeBases_and_RAG/1_managed-rag-kb-retrieve-generate-api.ipynb
- 02_KnowledgeBases_and_RAG/2_Langchain-rag-retrieve-api-mistral-and-claude-3-haiku.ipynb
- 02_KnowledgeBases_and_RAG/3_Langchain-rag-retrieve-api-claude-3.ipynb
> changing FM to Calude 3

- 02_KnowledgeBases_and_RAG/0_create_ingest_documents_test_kb.ipynb
- 02_KnowledgeBases_and_RAG/1_managed-rag-kb-retrieve-generate-api.ipynb
- 02_KnowledgeBases_and_RAG/2_Langchain-rag-retrieve-api-mistral-and-claude-3-haiku.ipynb
- 02_KnowledgeBases_and_RAG/3_Langchain-rag-retrieve-api-claude-3.ipynb
- 02_KnowledgeBases_and_RAG/4_CLEAN_UP.ipynb
Updated RAG workshop with the following changes:
use %store variable to store and retrieve variables throughout the labs and clean up.
> updated RAG workshop with storing variables and cleanup steps

- 02_KnowledgeBases_and_RAG/4_CLEAN_UP.ipynb
*Description of changes:
Fixed a minor issue with region not found error in the Clean up notebook. 
> Fixed RAG workshop cleanup region issue

- 02_KnowledgeBases_and_RAG/3_Langchain-rag-retrieve-api-claude-3.ipynb
> upgrade deprecated RetrievalQA

- 02_KnowledgeBases_and_RAG/0_create_ingest_documents_test_kb.ipynb
- 02_KnowledgeBases_and_RAG/2_Langchain-rag-retrieve-api-mistral-and-claude-3-haiku.ipynb
- 02_KnowledgeBases_and_RAG/3_Langchain-rag-retrieve-api-claude-3.ipynb
- 02_KnowledgeBases_and_RAG/4_CLEAN_UP.ipynb
> adding langchain-aws pip install

- 06_OpenSource_examples/cross-region-inference/Getting_started_with_Cross-region_Inference.ipynb
- 06_OpenSource_examples/cross-region-inference/README.md
> fixed the read me file

- 04_Image_and_Multimodal/bedrock-titan-image-generator.ipynb
Fix a minor issue with inpainting
> Fix a minor issue with TIG v1

- 01_Text_generation/00_text_generation_w_bedrock.ipynb
> refactor: :art: black linting

- 06_OpenSource_examples/cross-region-inference/Getting_started_with_Cross-region_Inference.ipynb
> created the default profile

- 06_OpenSource_examples/02_Langchain_Chatbot_examples/00_medibot_3V_agents.ipynb
- 06_OpenSource_examples/02_Langchain_Chatbot_examples/00_medibot_V3_memory_rag.ipynb
- 06_OpenSource_examples/02_Langchain_Chatbot_examples/00_medibot_V3_prompts.ipynb
Added three notebooks that breakdown chatbot design by stacking prompting, memory, rag and agentic workflows.
> chatbot notebook breakdown and enhancements

- 04_Image_and_Multimodal/bedrock-titan-image-generator.ipynb
> Updated notebook for TIG v1

- 02_KnowledgeBases_and_RAG/0_create_ingest_documents_test_kb.ipynb
- 02_KnowledgeBases_and_RAG/1_managed-rag-kb-retrieve-generate-api.ipynb
- 02_KnowledgeBases_and_RAG/2_Langchain-rag-retrieve-api-mistral-and-claude-3-haiku.ipynb
- 02_KnowledgeBases_and_RAG/3_Langchain-rag-retrieve-api-claude-3.ipynb
- 02_KnowledgeBases_and_RAG/4_CLEAN_UP.ipynb
- 02_KnowledgeBases_and_RAG/requirements.txt
- 02_KnowledgeBases_and_RAG/utility.py
> clean up test

- 04_Image_and_Multimodal/README.md
- 04_Image_and_Multimodal/bedrock-titan-image-generator-v2.ipynb
- 04_Image_and_Multimodal/bedrock-titan-image-generator.ipynb
- 04_Image_and_Multimodal/bedrock-titan-multimodal-embeddings.ipynb
> update 04_Image_and_Multimodal setup instructions

- 06_OpenSource_examples/02_Langchain_Chatbot_examples/00_medibot_V3.ipynb
> added changes to medibot versions

- 04_Image_and_Multimodal/AmazonNova/NovaReel/00-NovaReel-prerequisites.ipynb
Add boto3 version update to NovaReel
> Add boto3 version update

- 06_OpenSource_examples/text-generation-with-langchain/04_long_text_summarization_using_LCEL_chains_on_langchain.ipynb
N/A
last cell of the long text summarization had a bug where it was printing out the full shareholder letter not the Map-Reduced summary.
With updates, map reduce summery is printed and the shareholder letter is also printed for reference separately  
> Open Source - Long Text Summarization Example Fixed Up 

- RELEASE_NOTES.md
> V2.1 update of RELEASE_NOTES.md

- 03_Model_customization/bedrock-models-fine-tuning/claude-haiku/01_setup.ipynb
- 03_Model_customization/bedrock-models-fine-tuning/claude-haiku/02_fine-tune_Claude_Haiku.ipynb
Replace CNN dataset by Samsum dataset from HF
> Update Haiku FT Dataset
